-- SimForge preset simulations seed
-- Run AFTER schema.sql

DELETE FROM public.simulations WHERE is_preset = true;

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-brownian', 'Brownian Motion', 'Large tracer particle buffeted by gas molecules. Demonstrates kinetic theory — temperature equals average molecular kinetic energy.', '🌡️', 'physics',
  'function defineParameters(){return[{name:"temperature",type:"slider",min:50,max:500,default:200,step:10},{name:"gasParticles",type:"slider",min:20,max:200,default:80,step:5},{name:"particleSize",type:"slider",min:8,max:30,default:18,step:1},{name:"tracerTrail",type:"slider",min:0,max:1,default:1,step:1}];}
function init(p){const e=[];for(let i=0;i<p.gasParticles;i++){const spd=(Math.random()*.5+.75)*Math.sqrt(p.temperature)*.18,a=Math.random()*Math.PI*2;e.push({id:i,type:''gas'',x:Math.random()*760+20,y:Math.random()*510+20,vx:Math.cos(a)*spd,vy:Math.sin(a)*spd,radius:4,shape:''circle'',color:''#4a9eff''});}e.push({id:p.gasParticles,type:''tracer'',x:400,y:275,vx:0,vy:0,radius:p.particleSize,mass:20,shape:''circle'',color:''#f5a623'',trail:[]});return e;}
function update(entities,p){const W=800,H=550,tracer=entities.find(e=>e.type===''tracer''),gas=entities.filter(e=>e.type===''gas''),tgt=Math.sqrt(p.temperature)*.18;const ng=gas.map(e=>{let{x,y,vx,vy,radius}=e;const spd=Math.sqrt(vx*vx+vy*vy)||1;const sc=(tgt*(.75+Math.random()*.5))/spd;vx*=.98+.02*sc;vy*=.98+.02*sc;x+=vx;y+=vy;if(x<radius){x=radius;vx=Math.abs(vx);}if(x>W-radius){x=W-radius;vx=-Math.abs(vx);}if(y<radius){y=radius;vy=Math.abs(vy);}if(y>H-radius){y=H-radius;vy=-Math.abs(vy);}const dx=x-tracer.x,dy=y-tracer.y,dist=Math.sqrt(dx*dx+dy*dy),min=radius+tracer.radius;if(dist<min&&dist>0){const nx=dx/dist,ny=dy/dist,rv=(vx-tracer.vx)*nx+(vy-tracer.vy)*ny;if(rv<0){const imp=2*rv/(1+1/tracer.mass);vx-=imp*nx;vy-=imp*ny;tracer.vx+=(imp/tracer.mass)*nx;tracer.vy+=(imp/tracer.mass)*ny;const ov=min-dist;x+=nx*ov*.6;y+=ny*ov*.6;}}const heat=Math.min(Math.sqrt(vx*vx+vy*vy)/(tgt*1.5),1);return{...e,x,y,vx,vy,color:`hsl(${200-heat*160},70%,60%)`};});let tx=tracer.x+tracer.vx,ty=tracer.y+tracer.vy;tracer.vx*=.995;tracer.vy*=.995;if(tx<tracer.radius){tx=tracer.radius;tracer.vx=Math.abs(tracer.vx);}if(tx>W-tracer.radius){tx=W-tracer.radius;tracer.vx=-Math.abs(tracer.vx);}if(ty<tracer.radius){ty=tracer.radius;tracer.vy=Math.abs(tracer.vy);}if(ty>H-tracer.radius){ty=H-tracer.radius;tracer.vy=-Math.abs(tracer.vy);}const trail=p.tracerTrail>=.5?[...(tracer.trail||[]),{x:tracer.x,y:tracer.y}].slice(-120):[];return[...ng,{...tracer,x:tx,y:ty,trail}];}',
  NULL, true, true, 'brownian', '["Kinetic theory","Temperature","Molecular collisions","Thermodynamics"]'::jsonb, '["Understand why particles move faster at higher temperatures","Observe that larger particles diffuse more slowly","Connect microscopic motion to macroscopic temperature"]'::jsonb, '[{"n":"temperature","d":"Controls average kinetic energy of gas molecules"},{"n":"gasParticles","d":"Number of invisible gas molecules"},{"n":"particleSize","d":"Radius of the observable tracer particle"},{"n":"tracerTrail","d":"Toggle to show the random walk path of the tracer"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-electric', 'Electric Fields', 'Point charges create vector fields. Field line density shows strength. Visualises Coulomb''s law and superposition.', '⚡', 'physics',
  'function defineParameters(){return[{name:"charge1",type:"slider",min:-5,max:5,default:3,step:.5},{name:"charge2",type:"slider",min:-5,max:5,default:-3,step:.5},{name:"charge3",type:"slider",min:-5,max:5,default:0,step:.5},{name:"tracers",type:"slider",min:20,max:300,default:120,step:10},{name:"trailLen",type:"slider",min:5,max:60,default:25,step:5}];}
function chargeColor(q){if(q===0)return''#555566'';return q>0?`hsl(10,90%,${30+Math.abs(q)*8}%)`:`hsl(210,90%,${30+Math.abs(q)*8}%)`;}
function init(p){const e=[];e.push({id:''C1'',type:''charge'',x:220,y:275,q:p.charge1,shape:''circle'',radius:14,color:chargeColor(p.charge1),label:p.charge1>0?''+'':''−''});e.push({id:''C2'',type:''charge'',x:580,y:275,q:p.charge2,shape:''circle'',radius:14,color:chargeColor(p.charge2),label:p.charge2>0?''+'':''−''});e.push({id:''C3'',type:''charge'',x:400,y:150,q:p.charge3,shape:''circle'',radius:14,color:chargeColor(p.charge3),label:p.charge3>0?''+'':p.charge3<0?''−'':''·''});for(let i=0;i<p.tracers;i++)e.push({id:''T''+i,type:''tracer'',x:Math.random()*720+40,y:Math.random()*470+40,vx:0,vy:0,radius:2,shape:''circle'',color:''rgba(255,255,255,0.6)'',trail:[]});return e;}
function update(entities,p){const charges=entities.filter(e=>e.type===''charge'');const tracers=entities.filter(e=>e.type===''tracer'');const nc=charges.map((c,i)=>{const q=[p.charge1,p.charge2,p.charge3][i];return{...c,q,color:chargeColor(q),label:q>0?''+'':q<0?''−'':''·''};});const nt=tracers.map(e=>{let fx=0,fy=0;nc.forEach(c=>{if(c.q===0)return;const dx=e.x-c.x,dy=e.y-c.y,r2=dx*dx+dy*dy,r=Math.sqrt(r2)||1;if(r<c.radius+2)return;const f=c.q/(r2+200);fx+=(dx/r)*f;fy+=(dy/r)*f;});const fm=Math.sqrt(fx*fx+fy*fy)||1;let nx=e.x+(fx/fm)*2.5,ny=e.y+(fy/fm)*2.5;const near=nc.some(c=>{const dx=nx-c.x,dy=ny-c.y;return Math.sqrt(dx*dx+dy*dy)<c.radius+4;});if(nx<2||nx>798||ny<2||ny>548||near){return{...e,x:Math.random()*720+40,y:Math.random()*470+40,trail:[]};}const trail=[...(e.trail||[]),{x:e.x,y:e.y}].slice(-p.trailLen);const lf=Math.min(Math.log(fm*500+1)/6,1);return{...e,x:nx,y:ny,trail,color:`hsla(${200-lf*160},80%,65%,0.7)`};});return[...nc,...nt];}',
  NULL, true, true, 'electric', '["Coulomb''s law","Electric field","Superposition","Field line density"]'::jsonb, '["Understand that field line density represents field strength","See how multiple charges superpose their fields","Predict field shape for dipoles and like-charges"]'::jsonb, '[{"n":"charge1","d":"Magnitude of left charge (negative = attractive)"},{"n":"charge2","d":"Magnitude of right charge"},{"n":"charge3","d":"Magnitude of top charge (set 0 to remove)"},{"n":"tracers","d":"Number of field line particles"},{"n":"trailLen","d":"Length of each particle trail"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-gravity', 'Orbital Gravity', 'N-body gravitational simulation. Bodies attract each other with F=Gm₁m₂/r². Observe stable orbits, slingshots and collisions.', '🌌', 'physics',
  'function defineParameters(){return[{name:"bodies",type:"slider",min:2,max:20,default:6,step:1},{name:"G",type:"slider",min:100,max:5000,default:1000,step:100},{name:"trailLen",type:"slider",min:0,max:60,default:20,step:5}];}
function init(p){const colors=[''#ff6b6b'',''#ffd93d'',''#6bcb77'',''#4d96ff'',''#ff922b'',''#cc5de8'',''#f06595'',''#74c0fc''];const out=[];for(let i=0;i<p.bodies;i++){const a=(i/p.bodies)*Math.PI*2,r=120+Math.random()*100,mass=20+Math.random()*60,spd=Math.sqrt(p.G*200/r)*.4;out.push({x:400+Math.cos(a)*r,y:275+Math.sin(a)*r,vx:-Math.sin(a)*spd,vy:Math.cos(a)*spd,mass,radius:Math.sqrt(mass)*1.5,shape:''circle'',color:colors[i%colors.length],trail:[]});}return out;}
function update(entities,p){return entities.map((e,i)=>{let ax=0,ay=0;for(let j=0;j<entities.length;j++){if(i===j)continue;const dx=entities[j].x-e.x,dy=entities[j].y-e.y,d=Math.sqrt(dx*dx+dy*dy)+10,f=p.G*entities[j].mass/(d*d+100);ax+=(dx/d)*f;ay+=(dy/d)*f;}const nvx=e.vx+ax*.3,nvy=e.vy+ay*.3,nx=e.x+nvx*.3,ny=e.y+nvy*.3;const trail=[...(e.trail||[]),{x:e.x,y:e.y}].slice(-p.trailLen);return{...e,x:nx,y:ny,vx:nvx,vy:nvy,trail};});}',
  NULL, true, true, 'gravity', '["Gravitational force","Inverse square law","Orbital mechanics","Conservation of momentum"]'::jsonb, '["See how mass and distance affect gravitational force","Observe how initial velocity determines orbit shape","Explore why planetary systems form stable configurations"]'::jsonb, '[{"n":"bodies","d":"Number of gravitating bodies"},{"n":"G","d":"Gravitational constant — increase for faster, stronger interactions"},{"n":"trailLen","d":"Length of orbital trail per body"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-enzyme', 'Enzyme Kinetics', 'Michaelis-Menten kinetics visualised. Substrate molecules collide with enzymes to form ES complexes, then release products.', '🔬', 'chemistry',
  'function defineParameters(){return[{name:"substrateCount",type:"slider",min:10,max:200,default:80,step:5},{name:"enzymeCount",type:"slider",min:2,max:30,default:10,step:1},{name:"bindRate",type:"slider",min:.01,max:.3,default:.12,step:.01},{name:"catalysisRate",type:"slider",min:.005,max:.1,default:.02,step:.005},{name:"releaseRate",type:"slider",min:.01,max:.2,default:.05,step:.01}];}
function init(p){const e=[];for(let i=0;i<p.substrateCount;i++){const a=Math.random()*Math.PI*2,s=1.2+Math.random()*1.5;e.push({id:''S''+i,type:''substrate'',x:Math.random()*760+20,y:Math.random()*510+20,vx:Math.cos(a)*s,vy:Math.sin(a)*s,radius:5,shape:''circle'',color:''#4a9eff'',bound:false,boundTo:null});}for(let i=0;i<p.enzymeCount;i++)e.push({id:''E''+i,type:''enzyme'',x:80+(i%5)*140,y:80+Math.floor(i/5)*130,vx:0,vy:0,radius:18,shape:''circle'',color:''#3ecf8e'',occupied:false,occupiedBy:null,timer:0,label:''E''});return e;}
function update(entities,p){const W=800,H=550;const substrates=entities.filter(e=>e.type===''substrate'');const enzymes=entities.filter(e=>e.type===''enzyme'');const products=entities.filter(e=>e.type===''product'');const ne=enzymes.map(e=>{const en={...e};if(en.occupied){en.timer++;en.color=''#f5a623'';en.label=''ES'';if(Math.random()<p.catalysisRate){en.occupied=false;en.occupiedBy=null;en.timer=0;en.color=''#3ecf8e'';en.label=''E'';const sub=substrates.find(s=>s.id===e.occupiedBy);if(sub)sub._convert=true;}}return en;});const ns=[];substrates.forEach(e=>{if(e._convert){ns.push({...e,type:''product'',color:''#f5a623'',vx:(Math.random()-.5)*2,vy:(Math.random()-.5)*2,radius:4,bound:false,boundTo:null,_convert:false});return;}let{x,y,vx,vy,bound}=e;const en={...e};if(bound){const eg=ne.find(z=>z.id===e.boundTo);if(eg){en.x=eg.x+(Math.random()-.5)*4;en.y=eg.y+(Math.random()-.5)*4;}ns.push(en);return;}x+=vx;y+=vy;if(x<5){x=5;vx=Math.abs(vx);}if(x>W-5){x=W-5;vx=-Math.abs(vx);}if(y<5){y=5;vy=Math.abs(vy);}if(y>H-5){y=H-5;vy=-Math.abs(vy);}for(const eg of ne){if(eg.occupied)continue;const dx=x-eg.x,dy=y-eg.y;if(Math.sqrt(dx*dx+dy*dy)<eg.radius+6&&Math.random()<p.bindRate){en.bound=true;en.boundTo=eg.id;en.color=''#7c6af7'';eg.occupied=true;eg.occupiedBy=e.id;break;}}ns.push({...en,x,y,vx,vy});});const np=products.map(e=>{let{x,y,vx,vy}=e;x+=vx;y+=vy;vx*=.99;vy*=.99;if(x<5||x>W-5)vx*=-1;if(y<5||y>H-5)vy*=-1;return{...e,x,y,vx,vy};});return[...ns,...ne,...np];}',
  NULL, true, true, 'enzyme', '["Michaelis-Menten kinetics","Enzyme saturation","Active site binding","Km and Vmax"]'::jsonb, '["Observe enzyme saturation at high substrate concentrations","Understand why reaction rate plateaus (Vmax)","See the ES complex formation and product release cycle"]'::jsonb, '[{"n":"substrateCount","d":"Number of substrate molecules — increase to observe saturation"},{"n":"enzymeCount","d":"Number of enzyme molecules"},{"n":"bindRate","d":"Probability of binding when substrate meets enzyme"},{"n":"catalysisRate","d":"Rate at which ES complex converts to product"},{"n":"releaseRate","d":"How quickly product detaches from enzyme"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-diffusion', 'Molecular Diffusion', 'Random walk / Brownian motion. Particles diffuse from high to low concentration. Demonstrates Fick''s law qualitatively.', '💧', 'chemistry',
  'function defineParameters(){return[{name:"particles",type:"slider",min:100,max:2000,default:600,step:50},{name:"stepSize",type:"slider",min:.5,max:5,default:1.5,step:.1},{name:"drift",type:"slider",min:-2,max:2,default:0,step:.1},{name:"colorAge",type:"slider",min:0,max:1,default:1,step:1}];}
function init(p){return Array.from({length:p.particles},()=>({x:400,y:275,age:0,radius:2.5,shape:''circle'',color:''#7c6af7''}));}
function update(entities,p){return entities.map(e=>{const a=Math.random()*Math.PI*2;let nx=e.x+Math.cos(a)*p.stepSize+p.drift*.1,ny=e.y+Math.sin(a)*p.stepSize;const age=e.age+1;if(nx<0||nx>800||ny<0||ny>550){nx=400;ny=275;}let color=''#7c6af7'';if(p.colorAge>=.5){const t=Math.min(age/300,1);color=`rgb(${Math.round(124+(255-124)*t)},${Math.round(106+(75-106)*t)},${Math.round(247+(75-247)*t)})`;}return{...e,x:nx,y:ny,age,color};});}',
  NULL, true, true, 'diffusion', '["Fick''s law","Concentration gradient","Random walk","Entropy"]'::jsonb, '["Observe that particles spread from high to low concentration","Understand that diffusion doesn''t require active transport","See how temperature (step size) affects diffusion rate"]'::jsonb, '[{"n":"particles","d":"Number of diffusing molecules"},{"n":"stepSize","d":"Distance per step — analogous to temperature"},{"n":"drift","d":"Directional bias — simulates a concentration gradient"},{"n":"colorAge","d":"Toggle age-based colouring to see diffusion distance"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-sir', 'Virus Spread (SIR)', 'Susceptible-Infected-Recovered epidemic model. The gold standard for understanding how diseases spread through populations.', '🦠', 'biology',
  'function defineParameters(){return[{name:"population",type:"slider",min:50,max:500,default:200,step:10},{name:"infectionRate",type:"slider",min:.01,max:.5,default:.15,step:.01},{name:"recoveryRate",type:"slider",min:.001,max:.05,default:.01,step:.001},{name:"moveSpeed",type:"slider",min:.5,max:4,default:1.5,step:.1},{name:"initialInfected",type:"number",min:1,max:20,default:3}];}
function init(p){const out=[];for(let i=0;i<p.population;i++){out.push({x:Math.random()*780+10,y:Math.random()*530+10,vx:(Math.random()-.5)*p.moveSpeed*2,vy:(Math.random()-.5)*p.moveSpeed*2,state:i<p.initialInfected?''I'':''S'',radius:5,shape:''circle''});}return out;}
function update(entities,p){return entities.map((e,i)=>{const ne={...e};ne.x+=ne.vx;ne.y+=ne.vy;if(ne.x<5||ne.x>795)ne.vx*=-1;if(ne.y<5||ne.y>545)ne.vy*=-1;ne.x=Math.max(5,Math.min(795,ne.x));ne.y=Math.max(5,Math.min(545,ne.y));if(ne.state===''S''){for(let j=0;j<entities.length;j++){if(entities[j].state===''I''){const dx=ne.x-entities[j].x,dy=ne.y-entities[j].y;if(Math.sqrt(dx*dx+dy*dy)<14&&Math.random()<p.infectionRate){ne.state=''I'';break;}}}}else if(ne.state===''I''){if(Math.random()<p.recoveryRate)ne.state=''R'';}ne.color=ne.state===''S''?''#4a9eff'':ne.state===''I''?''#ff4a4a'':''#3ecf8e'';return ne;});}',
  NULL, true, true, 'sir', '["SIR model","Herd immunity","R-naught (R₀)","Epidemiology"]'::jsonb, '["Understand what R₀ means and how it drives epidemic growth","Discover the herd immunity threshold","See why flattening the curve matters"]'::jsonb, '[{"n":"population","d":"Total number of individuals in the simulation"},{"n":"infectionRate","d":"Probability of transmission per contact (drives R₀)"},{"n":"recoveryRate","d":"Rate at which infected individuals recover"},{"n":"moveSpeed","d":"How fast individuals move"},{"n":"initialInfected","d":"Number of individuals infected at the start"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-lotka', 'Predator-Prey', 'Spatial Lotka-Volterra model. Rabbits and foxes populations oscillate out of phase — the fundamental cycle of ecology.', '🦊', 'biology',
  'function defineParameters(){return[{name:"birthRateRabbit",type:"slider",min:.001,max:.02,default:.006,step:.001},{name:"deathRateRabbit",type:"slider",min:.001,max:.02,default:.006,step:.001},{name:"birthRateFox",type:"slider",min:.001,max:.01,default:.003,step:.001},{name:"deathRateFox",type:"slider",min:.001,max:.02,default:.008,step:.001},{name:"visionRadius",type:"slider",min:20,max:120,default:60,step:5}];}
function init(p){const e=[];for(let i=0;i<80;i++){const a=Math.random()*Math.PI*2;e.push({id:Math.random(),type:''rabbit'',x:Math.random()*760+20,y:Math.random()*510+20,vx:Math.cos(a)*1.2,vy:Math.sin(a)*1.2,radius:5,shape:''circle'',color:''#e8e8f0'',energy:80+Math.random()*40});}for(let i=0;i<15;i++){const a=Math.random()*Math.PI*2;e.push({id:Math.random(),type:''fox'',x:Math.random()*760+20,y:Math.random()*510+20,vx:Math.cos(a)*1.6,vy:Math.sin(a)*1.6,radius:8,shape:''triangle'',color:''#f5832a'',energy:100+Math.random()*50,angle:a});}return e;}
function update(entities,p){const W=800,H=550,rabbits=entities.filter(e=>e.type===''rabbit''),foxes=entities.filter(e=>e.type===''fox''),out=[];rabbits.forEach(e=>{let{x,y,vx,vy,energy}=e;let flee=null,fd=p.visionRadius;foxes.forEach(f=>{const dx=f.x-x,dy=f.y-y,d=Math.sqrt(dx*dx+dy*dy);if(d<fd){flee=f;fd=d;}});if(flee){const dx=x-flee.x,dy=y-flee.y,d=Math.sqrt(dx*dx+dy*dy)||1;vx+=(dx/d)*.3;vy+=(dy/d)*.3;}else{vx+=(Math.random()-.5)*.3;vy+=(Math.random()-.5)*.3;}const spd=Math.sqrt(vx*vx+vy*vy)||1;if(spd>1.8){vx=(vx/spd)*1.8;vy=(vy/spd)*1.8;}x+=vx;y+=vy;if(x<5){x=5;vx=Math.abs(vx);}if(x>W-5){x=W-5;vx=-Math.abs(vx);}if(y<5){y=5;vy=Math.abs(vy);}if(y>H-5){y=H-5;vy=-Math.abs(vy);}energy=Math.min(energy-.15+.08,150);if(energy<=0)return;const ne={...e,x,y,vx,vy,energy};if(energy>120&&Math.random()<p.birthRateRabbit){out.push({...ne,id:Math.random(),x:x+Math.random()*10-5,y:y+Math.random()*10-5,vx:Math.cos(Math.random()*Math.PI*2)*1.2,vy:Math.sin(Math.random()*Math.PI*2)*1.2,energy:60});ne.energy=70;}out.push(ne);});foxes.forEach(e=>{let{x,y,vx,vy,energy}=e;let prey=null,pd=p.visionRadius;rabbits.forEach(r=>{const dx=r.x-x,dy=r.y-y,d=Math.sqrt(dx*dx+dy*dy);if(d<pd){prey=r;pd=d;}});if(prey){const dx=prey.x-x,dy=prey.y-y,d=Math.sqrt(dx*dx+dy*dy)||1;vx+=(dx/d)*.35;vy+=(dy/d)*.35;if(d<12){energy+=60;const ri=rabbits.indexOf(prey);if(ri>-1)rabbits.splice(ri,1);const ni=out.findIndex(n=>n.id===prey.id);if(ni>-1)out.splice(ni,1);}}else{vx+=(Math.random()-.5)*.4;vy+=(Math.random()-.5)*.4;}const spd=Math.sqrt(vx*vx+vy*vy)||1;if(spd>2.2){vx=(vx/spd)*2.2;vy=(vy/spd)*2.2;}x+=vx;y+=vy;if(x<5){x=5;vx=Math.abs(vx);}if(x>W-5){x=W-5;vx=-Math.abs(vx);}if(y<5){y=5;vy=Math.abs(vy);}if(y>H-5){y=H-5;vy=-Math.abs(vy);}energy-=.3;if(energy<=0)return;const er=Math.min(energy/150,1),ne={...e,x,y,vx,vy,energy,angle:Math.atan2(vy,vx),color:`hsl(${25+er*15},85%,${35+er*20}%)`};if(energy>140&&Math.random()<p.birthRateFox){out.push({...ne,id:Math.random(),energy:80});ne.energy=80;}out.push(ne);});return out.length>0?out:init(p);}',
  NULL, true, true, 'lotka', '["Lotka-Volterra equations","Population oscillation","Carrying capacity","Trophic cascade"]'::jsonb, '["Observe the classic out-of-phase population cycle","Find parameter values that cause extinction","Understand why removing predators can destabilise ecosystems"]'::jsonb, '[{"n":"birthRateRabbit","d":"Rate at which rabbits reproduce"},{"n":"deathRateRabbit","d":"Natural rabbit death rate"},{"n":"birthRateFox","d":"Rate at which foxes reproduce (requires eating)"},{"n":"deathRateFox","d":"Fox starvation rate"},{"n":"visionRadius","d":"How far foxes and rabbits can see"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-wildfire', 'Wildfire Spread', 'Forest fire cellular automaton. Trees grow, lightning ignites fires, wind drives spread. Models real wildfire dynamics.', '🔥', 'biology',
  'function defineParameters(){return[{name:"growthRate",type:"slider",min:.001,max:.05,default:.008,step:.001},{name:"lightningRate",type:"slider",min:.0001,max:.005,default:.0005,step:.0001},{name:"spreadRate",type:"slider",min:.1,max:1,default:.6,step:.05},{name:"windX",type:"slider",min:-1,max:1,default:.3,step:.05},{name:"cellSize",type:"slider",min:6,max:20,default:10,step:2}];}
function stateColor(s,h){if(s===''empty'')return''#1a1d12'';if(s===''tree'')return''#2d6a1f'';if(s===''ash'')return''#3a3530'';return`rgb(255,${Math.round(80+h*140)},${Math.round(h*60)})`;}
function init(p){const cs=p.cellSize,cols=Math.floor(800/cs),rows=Math.floor(550/cs),out=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const s=Math.random()<.55?''tree'':''empty'';out.push({x:c*cs,y:r*cs,col:c,row:r,cols,rows,cs,state:s,heat:0,shape:''rect'',radius:cs-1,height:cs-1,color:stateColor(s,0)});}return out;}
function update(entities,p){const{cols,rows}=entities[0];const fireSet=new Set();entities.forEach((e,i)=>{if(e.state===''fire'')fireSet.add(i);});return entities.map((e,i)=>{const ne={...e};if(ne.state===''empty''){if(Math.random()<p.growthRate)ne.state=''tree'';}else if(ne.state===''tree''){if(Math.random()<p.lightningRate){ne.state=''fire'';ne.heat=1;}else{const dirs=[[-1,0,1-p.windX*.4],[1,0,1+p.windX*.4],[0,-1,1],[0,1,1]];for(const[dr,dc,bias]of dirs){const nr=e.row+dr,nc=e.col+dc;if(nr<0||nr>=rows||nc<0||nc>=cols)continue;if(fireSet.has(nr*cols+nc)&&Math.random()<p.spreadRate*bias*.08){ne.state=''fire'';ne.heat=.8+Math.random()*.2;break;}}}}else if(ne.state===''fire''){ne.heat-=.015+Math.random()*.01;if(ne.heat<=0){ne.state=''ash'';ne.heat=0;}}else if(ne.state===''ash''){if(Math.random()<p.growthRate*.3)ne.state=''empty'';}ne.color=stateColor(ne.state,ne.heat);return ne;});}',
  NULL, true, true, 'wildfire', '["Cellular automaton","Percolation theory","Fire ecology","Environmental modelling"]'::jsonb, '["See how wind direction affects fire spread patterns","Discover the critical density threshold for fire percolation","Understand why forest management matters for fire prevention"]'::jsonb, '[{"n":"growthRate","d":"Rate at which empty land regrows into forest"},{"n":"lightningRate","d":"Probability of lightning striking any tree"},{"n":"spreadRate","d":"Probability of fire spreading to adjacent trees"},{"n":"windX","d":"Wind direction and strength (positive = right)"},{"n":"cellSize","d":"Resolution of the grid"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-life', 'Conway''s Game of Life', 'Cellular automaton with four simple rules generating complex emergent patterns. Demonstrates emergence and computational universality.', '🔲', 'mathematics',
  'function defineParameters(){return[{name:"cellSize",type:"slider",min:4,max:20,default:8,step:2},{name:"density",type:"slider",min:.1,max:.7,default:.3,step:.05},{name:"speed",type:"slider",min:1,max:10,default:3,step:1}];}
function init(p){const cs=p.cellSize,cols=Math.floor(800/cs),rows=Math.floor(550/cs),out=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const alive=Math.random()<p.density;out.push({x:c*cs,y:r*cs,col:c,row:r,cols,rows,alive,shape:''rect'',radius:cs-1,height:cs-1,color:alive?''#7c6af7'':''transparent'',speedCtr:0});}return out;}
function update(entities,p){const{cols,rows}=entities[0],alive=new Set(entities.filter(e=>e.alive).map(e=>e.row*cols+e.col)),steps=Math.max(1,Math.round(11-p.speed));return entities.map(e=>{const ne={...e};ne.speedCtr=(ne.speedCtr||0)+1;if(ne.speedCtr<steps){ne.color=ne.alive?''#7c6af7'':''transparent'';return ne;}ne.speedCtr=0;let n=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(dr===0&&dc===0)continue;const r=((e.row+dr)+rows)%rows,c=((e.col+dc)+cols)%cols;if(alive.has(r*cols+c))n++;}ne.alive=ne.alive?(n===2||n===3):n===3;ne.color=ne.alive?''#7c6af7'':''transparent'';return ne;});}',
  NULL, true, true, 'life', '["Cellular automaton","Emergence","Turing completeness","Self-organisation"]'::jsonb, '["Observe how simple rules create complex, unpredictable patterns","Find stable structures (still lifes), oscillators, and gliders","Understand emergence — complexity from simplicity"]'::jsonb, '[{"n":"cellSize","d":"Grid resolution — smaller cells = more detail"},{"n":"density","d":"Initial fraction of live cells"},{"n":"speed","d":"Generations per frame"}]'::jsonb
);

INSERT INTO public.simulations (slug, name, description, icon, category, code, author_id, is_public, is_preset, preset_key, concepts, objectives, param_docs) VALUES (
  'preset-prisoners', 'Prisoner''s Dilemma', 'Spatial game theory — cooperators vs defectors. Each cell copies the most successful neighbour. Watch strategy patterns evolve.', '🎮', 'mathematics',
  'function defineParameters(){return[{name:"cellSize",type:"slider",min:4,max:16,default:8,step:2},{name:"b",type:"slider",min:1,max:2.5,default:1.65,step:.05},{name:"noise",type:"slider",min:0,max:.2,default:.02,step:.01},{name:"initDefect",type:"slider",min:.1,max:.9,default:.3,step:.05},{name:"speed",type:"slider",min:1,max:10,default:4,step:1}];}
function init(p){const cs=p.cellSize,cols=Math.floor(800/cs),rows=Math.floor(550/cs),out=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const d=Math.random()<p.initDefect;out.push({x:c*cs,y:r*cs,col:c,row:r,cols,rows,strategy:d?1:0,score:0,shape:''rect'',radius:cs-1,height:cs-1,color:d?''#e05252'':''#4a90d9''});}return out;}
function update(entities,p){const{cols,rows}=entities[0],b=p.b,steps=Math.max(1,Math.round(p.speed));let cur=entities;for(let s=0;s<steps;s++){const sc=cur.map((e,i)=>{let score=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(dr===0&&dc===0)continue;const nr=e.row+dr,nc=e.col+dc;if(nr<0||nr>=rows||nc<0||nc>=cols)continue;const nb=cur[nr*cols+nc];if(e.strategy===0&&nb.strategy===0)score+=1;else if(e.strategy===1&&nb.strategy===0)score+=b;}return{...e,score};});cur=sc.map((e,i)=>{let best=e;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const nr=e.row+dr,nc=e.col+dc;if(nr<0||nr>=rows||nc<0||nc>=cols)continue;const nb=sc[nr*cols+nc];if(nb.score>best.score)best=nb;}let strategy=best.strategy;if(Math.random()<p.noise)strategy=Math.random()<.5?0:1;const color=strategy===0?`hsl(${210+e.score*4},70%,${45+e.score*3}%)`:`hsl(${e.score*3},70%,${40+e.score*3}%)`;return{...e,strategy,color};});}return cur;}',
  NULL, true, true, 'prisoners', '["Game theory","Nash equilibrium","Evolutionary dynamics","Spatial games"]'::jsonb, '["Find the temptation value (b) where cooperators and defectors coexist","Observe that cooperators survive by clustering together","Understand why cooperation can be evolutionarily stable"]'::jsonb, '[{"n":"b","d":"Temptation to defect — the key parameter. Watch the phase transition around b=1.8"},{"n":"noise","d":"Random mutation rate — prevents lock-in"},{"n":"initDefect","d":"Starting fraction of defectors"},{"n":"cellSize","d":"Grid resolution"},{"n":"speed","d":"Generations per frame"}]'::jsonb
);

